### ISSUE TITLE
I am curious if this is true; participants from Antarctica.

### ISSUE THREAD

**Issue by sauparna** [vstrimaitis/google_codejam_stats#6]
Round 1A 2018 stats mentions Antarctica. If it is true this is wonderful or is this be a bug?

![Screenshot (3)](https://user-images.githubusercontent.com/91951/65898798-927c3780-e36f-11e9-94eb-4251d397d541.png)

**Comment by vstrimaitis** [comment]
Well, this is the data that I get from Google's APIs. So either some scientists solving GCJ or some people simply set their countries to something random 😄
